# Generated by Django 6.0.3 on 2026-09-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
    ]
